### ISSUE TITLE
could you put your result on the web？

### ISSUE THREAD

**Issue by dlongry** [zoharli/SRGAN-tensorflow#2]
Thank you for your work. I have using titui1990's SRGANs' work.But the reulst is not good.In fact, I have no time to train your work again. so...could you show me your SR images？Thanks.

**Comment by zoharli** [comment]
Mine didn't work well too, I'm trying to find the problem currently. SR images produced by my srResNet-mse now has an average psnr of 24~25dB , much lower than the official 31dB.
