### ISSUE TITLE
A error while pretraining

### ISSUE THREAD

**Issue by DunguLock** [zoharli/SRGAN-tensorflow#3]
Hi! I download the vgg19.npy  and put my own images in "r256-512.bin".
While trying to run "pretrain.py" file it gives me this traceback:
 File "/home/iecas/PycharmProjects/SRGAN-tensorflow-master/pretrain.py", line 49, in <module>
     resnet = srResNet.srResNet(rescaled)
 File "/home/iecas/PycharmProjects/SRGAN-tensorflow-master/pretrain.py", line 7, in __init__
    conv1 = conv_layer(T, [5, 5, 3, 64], 1)
 File "/home/iecas/PycharmProjects/SRGAN-tensorflow-master/pretrain.py", line 7, in conv_layer
    bias = tf.Variable(tf.zeros(conv.shape.as_list()[3], name='bias'))
AttributeError: 'Tensor' object has no attribute 'shape'

@zoharli

**Comment by zoharli** [comment]
What's your tensorflow version? Try to find a built-in function or attribte of Tensor Class that return the shape of the Tensor and then replace it.Typically,it's shape() ,then you can replace `conv.shape.as_list()` with `conv.shape().as_list()` .

**Comment by DunguLock** [comment]
My tensorflow version is 0.12, I replaced conv.shape.as_list() with conv.get_shape().as_list(). That's worked.Thank you! @zoharli . You said your result is not good, have you improved this model?
if you did some works in improving the result, can you put you method in this web?Thank you very much!

**Comment by zoharli** [comment]
I recently switched to pytorch and reimplemented SRGAN,because I thought tensorflow don't work well with SRGAN.But it turns out that the problem is the testing method I use, I didn't follow the standard way used in the paper.Actually the result is just fine,though not as good as presented in paper,but still better than bicubic upsampling.
Currently I'm still trying to fine tunning my result in pytorch , which has reached 27.3dB in BSD100 dataset .When I'm done,I'll update this tensorflow implementation as well,but that should take a while :)

**Comment by DunguLock** [comment]
@zoharli  many thanks!After solving the problem before, I meet another problem that as follows.
File  "/home/iecas/PycharmProjects/SRGAN-tensorflow-master/pretrain.py", line 58, in <module>
   with tf.Session() as sess:
File  "/home/iecas/PycharmProjects/SRGAN-tensorflow-master/pretrain.py", line 1186, in __init__
  super(Session, self).__init__(target, graph, config=config)
File  "/home/iecas/PycharmProjects/SRGAN-tensorflow-master/pretrain.py", line 551, in __init__
  self._session = tf_session.TF_NewDeprecatedSession(opts, status)
File "/home/iecas/PycharmProjects/SRGAN-tensorflow-master/pretrain.py, line 24, in __exit__
  self.gen.next()
File "/home/iecas/PycharmProjects/SRGAN-tensorflow-master/pretrain.py, line 469, in raise_exception_on_not_ok_status
  pywrap_tensorflow.TF_GetCode(status))
tensorfloe.python.framework.erors_impl.InternalError: Failed to creat session.
Can you help me to do with that one?

**Comment by zoharli** [comment]
I never encountered such problem, maybe you can try using tf.InteractiveSession() instead. One possible reason is that the CPU or GPU doesn't have enough resources for this session.By the way,I strongly recommend you upgrade tensorflow to 1.0 before running my project,there can be a lot of incompatibilities between 0.12 and 1.0.

**Comment by DunguLock** [comment]
Thank you very much!
